# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n97MF5Ln52bjMCqox_YYIlm0Nph4FRz8
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
from sklearn.linear_model import LinearRegression

# Load trained model
model = pickle.load(open('insurance_model.pkl', 'rb'))  # Make sure to have this file

st.title('Medical Insurance Cost Predictor')

st.write("### Enter User Details")

# User Inputs
age = st.slider('Age', 18, 100)
sex = st.selectbox('Sex', ('Male', 'Female'))
bmi = st.number_input('BMI', 10.0, 60.0)
children = st.slider('Number of Children', 0, 5)
smoker = st.selectbox('Smoker', ('No', 'Yes'))
region = st.selectbox('Region', ['Southeast', 'Southwest', 'Northeast', 'Northwest'])

# Convert inputs to model format
sex_code = 0 if sex == 'Male' else 1
smoker_code = 1 if smoker == 'Yes' else 0
region_map = {'Southeast': 0, 'Southwest': 1, 'Northeast': 2, 'Northwest': 3}
region_code = region_map[region]

# Optional interaction feature
bmi_smoker = bmi * smoker_code

# Predict button
if st.button('Predict Insurance Expense'):
    user_input = np.array([[age, sex_code, bmi, children, smoker_code, region_code, bmi_smoker]])
    prediction = model.predict(user_input)[0]
    st.success(f"Estimated Insurance Cost: ₹{prediction:.2f}")